### ISSUE TITLE
Defining some categories as static constants

### ISSUE THREAD

**Issue by anubh-v** [CS2103-AY1819S1-W17-1/main#78]
For these category names, `~work`, `~education`, and `~projects`, is it better if we define them as static constants in the Category class?

Reasons:
- I will likely reuse them when I generate pre-filled ResumeEntries for SoC / NUS awareness
- We may reuse them when writing tests? 

![image](https://user-images.githubusercontent.com/35621759/46719002-8bac6e80-cc9f-11e8-92f7-3cf533853f6d.png)

What do you guys think? Which way would be better?

**Comment by ongspxm** [comment]
I am thinking of making category work like tags, two entries being in the
same category doesnt really mean they have the same Category. They both
have a Category and both Category equals one another.

I am planning to do all the filtering and matching in CategoryManager,
removing the need to match it within the class itself, the class only need
to have the equal function ready
